apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "my-bot.fullname" . | lower | trunc 63 | trimSuffix "-" }}-np
  labels:
    {{- include "my-bot.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous 
spec:
  podSelector:
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP 
      port: 5432

