apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-bot.fullname" . }}
  labels:
    {{- include "my-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-bot.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-bot.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.bot.existingSecret }} 
                  key: telegram-token
{{- with .Values.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 4 }}
{{- end }}
