apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-bot.fullname" . }}
  labels:
    {{- include "my-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-bot.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-bot.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imagebot.repository }}:{{ .Values.imagebot.tag }}"
          env:
          - name: TELEGRAM_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.bot.SecretTOKEN }} 
                  key: telegram-token
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.bot.SecretPSQL }} 
                  key: POSTGRES_DB
          
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.bot.SecretPSQL }} 
                  key: POSTGRES_PASSWORD
          
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                  name: {{ .Values.bot.SecretPSQL }} 
                  key: POSTGRES_USER
      nodeSelector:
        app: sleve 
{{- with .Values.nodeSelector }}
nodeSelector:
  {{- toYaml . | nindent 4 }}
{{- end }}
