apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-postgres.fullname" . | lower | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "my-postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-postgres.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-postgres.labels" . | nindent 8 }}
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.imagepsql.repository }}:{{ .Values.imagepsql.tag }}"
        imagePullPolicy: {{ .Values.postgresql.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.secretName }}
                key: POSTGRES_DB
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.secretName }}
                key: POSTGRES_PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.postgresql.auth.secretName }}
                key: POSTGRES_USER
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: botic-postgres-pvc                      