apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-postgres.fullname" . | lower | trunc 63 | trimSuffix "-" }}-pv
spec:
  capacity:
    storage: {{ .Values.postgresql.persistence.size | quote }}  
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgresql.persistence.storageClass | quote }} 
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres