apiVersion: v1
kind: PersistentVolume
metadata:
  name: manual-pv
spec:
  capacity:
    storage: 1Gi   
  accessModes:
    - ReadWriteOnce
  storageClassName: tg-bot-postgres
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres