apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-postgres.pvcName" . }}
  labels:
    {{- include "my-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: tg-bot-postgres
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}