apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-postgres.fullname" . | lower | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "my-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | default "1Gi" }}
  storageClassName: local-path