replicaCount: 2

image:
  repository: djabjo/telegram-bot
  tag: 0.0.32
  pullPolicy: Always

imagepsql:
  repository: postgres
  tag: "13"
  pullPolicy: Always

bot:
  name: "aiogram-bot"
  existingSecret: "aiogram-bot-secret"
  SecretPSQL: "postgres-secret"

postgresql:
  auth:
    secretName: "postgres-secret"
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"  
    existingClaim: "" 
  service:
    type: ClusterIP
    port: 5432

resources:
  limits:
    memory: "524Mi"
    cpu: "200m"
  requests:
    memory: "256Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}
