replicaCount: 1

image:
  repository: djabjo/telegram-bot
  tag: 0.0.24
  pullPolicy: Always

bot:
  name: "aiogram-bot"
  existingSecret: "aiogram-bot-secret"
  SecretPSQL: "postgres-secret"


resources:
  limits:
    memory: "1024Mi"
    cpu: "200m"
  requests:
    memory: "256Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}
