apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 
    {{- include "my-postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi