apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgresql-postgres
spec:
  podSelector:
    matchLabels:
      app: postgresql  # Должно совпадать с лейблами подов PostgreSQL
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports:
    - port: 5432
      protocol: TCP

  accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi 