apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-postgres.fullname" . | lower | trunc 63 | trimSuffix "-" }}-service
spec:
  selector:
    {{- include "my-postgres.labels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432
