replicaCount: 1
image:
  repository: postgres
  tag: "13"
  pullPolicy: Always

postgresql:
  auth:
    secretName: "postgres-secret"
  persistence:
    enabled: true
    size: 1Gi
    storageClass: "local-path"  
    existingClaim: "" 
  service:
    type: ClusterIP
    port: 5432

resources:
  limits:
    memory: "1024Mi"
    cpu: "200m"
  requests:
    memory: "256Mi"
    cpu: "100m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  
nodeSelector: {}

tolerations: []

affinity: {}