replicaCount: 1

image:
  repository: djabjo/telegram-bot
  tag: 1.2.2
  pullPolicy: Always

bot:
  name: "aiogram_bot"
  token: ${{ secrets.TELEGRAM_TOKEN }}  


resources:
  limits:
    memory: "1024Mi"
    cpu: "200m"
  requests:
    memory: "256Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}
