apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-bot.fullname" . | lower | trunc 63 | trimSuffix "-" }}-svc
  labels:
    {{- include "my-bot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "my-bot.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432