apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: {{ include "my-bot.fullname" . }}
   labels:
     {{- include "my-bot.labels" . | nindent 4 }}
 spec:
   replicas: {{ .Values.replicaCount }}
   selector:
     matchLabels:
       {{- include "my-bot.labels" . | nindent 6 }}
   template:
     metadata:
       labels:
         {{- include "my-bot.labels" . | nindent 8 }}
     spec:
       containers:
         - name: {{ .Chart.Name }}
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
           env:
             - name: TELEGRAM_BOT_TOKEN
               value: {{ .Values.bot.token }}
             - name: POSTGRES_URL
               value: {{ .Values.postgres.url | quote }}
             - name: POSTGRES_USER
               value: {{ .Values.postgres.user | quote }}
             - name: POSTGRES_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: {{ .Values.postgres.secretName }}
                   key: postgres-password
             - name: POSTGRES_DB
               value: {{ .Values.postgres.db | quote }} 
           resources:
             limits:
               memory: {{ .Values.resources.limits.memory }}
               cpu: {{ .Values.resources.limits.cpu }}
             requests:
               memory: {{ .Values.resources.requests.memory }}
               cpu: {{ .Values.resources.requests.cpu }}
             
           securityContext:
             allowPrivilegeEscalation: false
 {{- with .Values.nodeSelector }}
   nodeSelector:
     {{- toYaml . | nindent 4 }}
 {{- end }}
 {{- with .Values.affinity }}
   affinity:
     {{- toYaml . | nindent 4 }}
 {{- end }}
 {{- with .Values.tolerations }}
   tolerations:
     {{- toYaml . | nindent 4 }}
 {{- end }}