replicaCount: 1
imagebot:
  repository: djabjo/telegram-bot
  tag: 0.0.32
  pullPolicy: Always

imagepsql:
  repository: postgres
  tag: "13"
  pullPolicy: Always

bot:
  name: "aiogram-bot"
  existingSecret: "aiogram-bot-secret"
  SecretPSQL: "postgres-secret"

resources:
  limits:
    memory: "524Mi"
    cpu: "200m"
  requests:
    memory: "256Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}
