replicaCount: 1
imagebot:
  repository: djabjo/telegram-bot
  tag: 0.0.32
  pullPolicy: Always

postgresql:
  auth:
    secretName: "postgres-secret"
  persistence:
    enabled: true
    size: 1Gi
    storageClass: tg-bot-postgres
  service:
    type: ClusterIP
    port: 5432

imagepsql:
  repository: postgres
  tag: "13"
  pullPolicy: Always

bot:
  SecretTOKEN: "aiogram-bot-secret"
  SecretPSQL: "postgres-secret"

resources:
  limits:
    memory: "524Mi"
    cpu: "200m"
  requests:
    memory: "256Mi"
    cpu: "100m"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2

nodeSelector: {}

tolerations: []

affinity: {}
