apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-postgres.fullname" . | lower | trunc 63 | trimSuffix "-" }}-pv
spec:
  capacity:
    storage: 4Gi   
  accessModes:
    - ReadWriteOnce
  storageClassName: tg-bot-postgres  
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/postgres